### ISSUE TITLE
Document Hooks Usage

### ISSUE THREAD

**Issue by p3ck** [CentOS-PaaS-SIG/linchpin#747] opened 2018-10-22 18:51 UTC
What types of hooks are available.
The directory structure is tightly coupled with the naming of the hooks in the PinFile.  
What options/args are available, what does context: true mean?
etc..

**Comment by herlo** [comment] 2018-10-22 19:49
Duplicate of #684 ?

**Closed** 2018-10-25 14:32 UTC
