### ISSUE TITLE
Example OpenStack topology does not reflect updated credential changes

### ISSUE THREAD

**Issue by rywillia** [CentOS-PaaS-SIG/linchpin#317] opened 2017-07-20 14:33 UTC
The available OpenStack topology on the documentation [1] fails when trying to provision an individual resource. Here is my console output I am getting:

```
TASK [openstack : Initiating  Provisioning/Deprovioning of resources Openstack resource group] ***
included: /usr/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml for localhost

TASK [openstack : Unset the authvar from previous run] *************************
ok: [localhost]

TASK [openstack : set default_cred_profile when res_grp[credentials] is undefined] ***
ok: [localhost]

TASK [openstack : set default_cred_profile when res_grp[credentials] is undefined] ***
ok: [localhost]

TASK [openstack : set cred_profile when res_grp[credentials] is defined] *******
skipping: [localhost]

TASK [openstack : set default_cred_filename when res_grp[credentials] is defined] ***
skipping: [localhost]

TASK [openstack : Get creds from auth driver] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error: Credential not found"}
...ignoring

TASK [openstack : set auth_var] ************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'output'\n\nThe error appears to have been in '/usr/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml': line 35, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"set auth_var\"\n  ^ here\n"}
...ignoring

TASK [openstack : provisioning resource definitions of current group] **********
included: /usr/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml for localhost

TASK [openstack : provision resources of type os_server] ***********************
included: /usr/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml for localhost

TASK [openstack : provisioning os_server resources with provided auth] *********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: keystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_EpmrDB/ansible_module_os_server2.py\", line 764, in <module>\n    main()\n  File \"/tmp/ansible_EpmrDB/ansible_module_os_server2.py\", line 744, in main\n    cloud = shade.openstack_cloud(**cloud_params)\n  File \"/usr/lib/python2.7/site-packages/shade/__init__.py\", line 109, in openstack_cloud\n    cloud_config = config.get_one_cloud(**kwargs)\n  File \"/usr/lib/python2.7/site-packages/os_client_config/config.py\", line 1074, in get_one_cloud\n    auth_plugin = loader.load_from_options(**config['auth'])\n  File \"/usr/lib/python2.7/site-packages/keystoneauth1/loading/base.py\", line 162, in load_from_options\n    raise exceptions.MissingRequiredOptions(missing_required)\nkeystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url\n", "module_stdout": "", "msg": "MODULE FAILURE"}
	to retry, use: --limit @/usr/lib/python2.7/site-packages/linchpin/provision/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=17   changed=0    unreachable=0    failed=1   

```

My topology file is the following:

```
---
 topology_name: "openstack_topology"
 site: "qeos"
 resource_groups:
   -
     resource_group_name: "test_machine"
     res_group_type: "openstack"
     res_defs:
       - res_name: "test_machine"
         flavor: "m1.small"
         res_type: "os_server"
         image: "my_image"
         count: 1
         keypair: "my_keypair"
         networks:
           - "my_network"
     assoc_creds: "openstack"

```
Previously before 1.0 was released, I had to set the credentials file at the following path:

```
/usr/lib/python2.7/site-packages/linchpin/provision/roles/openstack/openstack.yml
```
It seems that this way of using credentials is deprecated in the latest release? I tried to place the credentials file within the credentials folder created by **linchpin init** and that still did not work (when giving the path --creds-path option).

After going through the source code and seeing the folllowing issue #273. I was able to provision my resource using the new credential structure for OpenStack in the issue above.

Could this way of setting credentials for OpenStack provider be documented? Will there be updated topology files to accommodate this? It would be nice to have for first time users trying to get started with linchpin.

[1] http://linchpin.readthedocs.io/en/v1.0.2/topologies_openstack.html#openstack-server

**Comment by herlo** [comment] 2017-07-21 15:28
Yes! The goal is to document the new credentials process. It's a pretty clear process, but given the manpower we have, it may take some time. Thanks for filing this though, so we have something to help track the progress.

**Comment by herlo** [comment] 2017-07-26 21:51
Duplicate of #315 methinks.

**Closed** 2017-07-26 21:51 UTC
Labels: duplicate
