### ISSUE TITLE
No IPs are rendered in inventory file if auto_ip:no is set for openstack provider

### ISSUE THREAD

**Issue by lukas-bednar** [CentOS-PaaS-SIG/linchpin#596] opened 2018-05-24 10:10 UTC
linchpin 1.5.4

I have following topology using openstack provider, and I don't want that VM will get floating IPs.
It is enough for my usecase to use internal IPs only. So I am setting `auto_ip: no` to skip FIP assignment. 
```yaml
---
topology_name: my_cluster
resource_groups:
  - resource_group_name: openstack
    resource_group_type: openstack
    resource_definitions:
      - name: "{{ executor_name }}-master"
        type: os_server
        flavor: w1.large
        image: "{{ image }}"
        count: 1
        keypair: "{{ keypair }}"
        networks:
          - "{{ network }}"
        auto_ip: no
        security_groups: "{{ security_group }}"
      - name: "{{ executor_name }}-node"
        type: os_server
        flavor: w1.large
        image: "{{ image }}"
        count: 2
        keypair: "{{ keypair }}"
        networks:
          - "{{ network }}"
        auto_ip: no
        security_groups: "{{ security_group }}"
    credentials:
      filename: clouds.yml
      profile: "{{ os_cloud }}"
```
and I have following layout where I want to render provisioned VMs with internal IPs
```yaml
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    "{{ executor_name }}-master":
      count: 1
      host_groups:
        - masters
        - etcd
        - nodes
        - nfs
        - glusterfs
    "{{ executor_name }}-node":
      count: 2
      host_groups:
        - nodes
        - glusterfs
  host_groups:
    OSEv3:
      children:
        - masters
        - nodes
        - etcd
        - nfs
        - glusterfs
```
but unfortunately the generated inventory file is empty
```
[glusterfs]
 hostname=

[masters]
 hostname=

[nfs]
 hostname=

[nodes]
 hostname=

[etcd]
 hostname=

[all]
 hostname=
```

Could you please help me to achieve my use case ?

**Comment by samvarankashyap** [comment] 2018-05-29 14:13
@lukas-bednar : When auto-ip is set to no The VM is not ensured to get the Public IP. (http://docs.ansible.com/ansible/latest/modules/os_server_module.html)
Linchpin inventory generation currently solely depends on the Public/Floating IPs not private IPs. 
In your case, Would you like to get the private IPs at hostname var ? or the actual hostname of the machine provisioned ?

**Comment by dyasny** [comment] 2018-05-29 14:18
The entire point of requesting to support "auto_ip: no" was to make use of internal IPs. If we can't get them, this request is not complete.

There is no differentiation between internal and floating IPs in the layout, all there is is "__IP__".

**Comment by lukas-bednar** [comment] 2018-05-29 14:35
> In your case, Would you like to get the private IPs at hostname var ? or the actual hostname of the machine provisioned ?

@samvarankashyap Yes, I was expecting to get internal IP, but as @dyasny pointed out, there is no differentiation between private / public IP ... and also what if I attach more then one Floating IP, or more network interfaces. This `__IP__` can not really cover it atm .

**Comment by 14rcole** [comment] 2018-08-29 13:55
@lukas-bednar I tried using your topology file to reproduce the issue but I couldn't do so.  Does this still occur for you?

**Comment by samvarankashyap** [comment] 2018-08-29 14:49
@14rcole The issue should be persistent . Have you tried the same topology used by @lukas-bednar ?

**Comment by 14rcole** [comment] 2018-08-29 15:38
@samvarankashyap yeah, I copied the topology.  The only changes I made were hardcoding the variables (e.g. keypair) and changing the instance type to m1.small because we didn't have enough free resources to create all those w1.large nodes.  I doubt either of those would have affected the output but I could be wrong

**Comment by 14rcole** [comment] 2018-08-29 19:16
@lukas-bednar update: I figured it out and can now reproduce the issue

**Comment by lukas-bednar** [comment] 2018-08-30 05:28
@14rcole Thanks for looking into that, I will try to reproduce that on Fri, putting on my list.

**Comment by herlo** [comment] 2018-10-02 15:42
@lukas-bednar can you confirm this is fixed and be closed? Thanks!

**Comment by lukas-bednar** [comment] 2018-10-03 11:20
@herlo yes it is fixed, thank you!

**Comment by herlo** [comment] 2018-10-03 14:08
Closing per comments above.

**Closed by herlo** 2018-10-03 14:08 UTC
Labels: bug, openstack
