### ISSUE TITLE
(3) Provide a way to specify cloud-init configs

### ISSUE THREAD

**Issue by jlebon** [CentOS-PaaS-SIG/linchpin#148] opened 2017-02-07 14:07 UTC
Linch-pin should provide a way for users to specify cloud-init configs (e.g. in the `os_server` case, through the `userdata` key).

**Comment by herlo** [comment] 2017-02-24 21:27
@jlebon, this looks like a duplicate of #76. No?

**Comment by jlebon** [comment] 2017-02-24 21:54
Hmm, doesn't look like it. #76 seems to be about giving users a better way to provide credentials, no? This issue is about being able to pass any random data (mostly for cloud-init) through the `userdata` key: http://docs.ansible.com/ansible/os_server_module.html

**Comment by herlo** [comment] 2017-02-27 16:26
Ok. I see. You want to provide logins, system configurations, etc. for the hosts. That makes more sense now. @samvarankashyap, do we have any plans to address this? I was thinking this would be an after effect, but I do wish to do something similar with libvirt using cloud-init.

**Comment by samvarankashyap** [comment] 2017-02-27 18:01
@herlo : IMO,  We can add one more key user_data to os_server res_def to enable the feature . 
Further, we might have to add the same key to aws_ec2 and gcloud_gce to make as ansible modules have support to do the same.

**Comment by herlo** [comment] 2017-03-21 16:35
@jlebon @samvarankashyap I think maybe this should be a feature where we allow 'extra data' to be passed as valid data to either the instances, or the providers (cloud provisioning modules). In issue #182, there's a request for beaker to set a value when provisioning to track it better. This could be useful as 'userdata' here, or as ephemeral data to a libvirt provider. 

Thoughts?

**Comment by herlo** [comment] 2017-05-24 19:00
This is similar to #111

**Comment by herlo** [comment] 2017-06-22 17:49
![](https://github.trello.services/images/mini-trello-icon.png) [Cloud-Init Functionality](https://trello.com/c/duaJgitw/13-cloud-init-functionality)

**Comment by herlo** [comment] 2017-07-26 15:44
os_server was completed by #291

**Closed by herlo** 2017-07-26 15:44 UTC
Labels: development, enhancement, openstack
