### ISSUE TITLE
Creating two OpenStack hosts fails

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linchpin#335] opened 2017-08-01 20:06 UTC
I'm trying to spin up two OpenStack hosts from the same topology which looks as follows:

```
---
topology_name: rhel7_rhel7_nosec_nossl
site: openstack
resource_groups:
  - resource_group_name: rhel7_rhel7
    res_group_type: openstack
    credentials:
      filename: clouds.yml
      profile: osp10
    res_defs:
      - res_name: nosec_nossl
        flavor: m1.medium
        res_type: os_server
        image: my-rhel-image
        count: 2
        keypair: ci-ops-central
        networks:
          - my_network
        fip_pool: 10.1.1.0
```

The only difference between this and a topology that works for me is ``count: 2`` instead of ``count: 1``.

**Comment by herlo** [comment] 2017-08-01 20:09
Can you provide output to show the error message? I can't really troubleshoot this without it. Thanks!

**Comment by greg-hellings** [comment] 2017-08-01 20:15
Error message: ``TASK [openstack : provisioning os_server resources with provided auth] *********
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": "(400) Client Error for url: https://ci-rhos.centralci.eng.rdu2.redhat.com:13774/v2.1/servers Bad network format: missing 'uuid'"}``

I'm working on debugging what's going on here, myself, as this is a blocker for my current task. Let me know if you have any sudden insights.

**Comment by herlo** [comment] 2017-08-01 20:27
This error seems unrelated to linchpin itself. It seems related directly to the openstack server. Maybe there's something we need to add regarding the uuid in the schema? 

Can you try this directly with the os_server module here and see if the issue persists?

http://docs.ansible.com/ansible/latest/os_server_module.html

**Comment by greg-hellings** [comment] 2017-08-02 20:31
So this behavior is intermittent. Running again and again, I get around an 80% failure rate with this error message. I've tried both in OpenStack versions 7 and 10. I'll try with the module, directly, next.

**Comment by greg-hellings** [comment] 2017-08-02 20:33
It also bears noting that linchpin does not use the os_server module, but instead uses the os_server2 module that it ships with its internal library.

**Comment by greg-hellings** [comment] 2017-08-03 00:48
OK, so a little more scouting brings the following salient points to light:
* This does not appear to afffect os_server, in my testing
* os_server is not in use by linchpin, anyway. It also does not support the ``count`` option, so it's not feasible to test this error on there
* linchpin uses os_server2.py from its own repository (linchpin/provision/library/os_server2.py) which introduces the ``count`` attribute

Why do we need a new os_server2.py file, instead of using the os_server.py module from upstream that would have the advantage of the entire community updating it, fixing it, etc? Surely we can manage to work within what os_server.py provides?

**Comment by herlo** [comment] 2017-08-07 15:13
Similar to #314, are these duplicates @samvarankashyap?

**Comment by samvarankashyap** [comment] 2017-08-07 19:01
@herlo yes 
#314 #338 are duplicates

**Comment by herlo** [comment] 2017-08-07 19:18
Duplicate of #314, closing this one and using that one to track the status of the fix.

**Closed by herlo** 2017-08-07 19:18 UTC
Labels: bug, duplicate
